title: COVID 19 forecast hub
baseurl: /covid19-forecast-hub-web/
permalink: '/:title/'
destination: docs
collections:
  posts:
    permalink: '/posts/:title/'
description: Your source for up-to-date forecasts of COVID-19.
palette: navy
palettes:
  blue:
    sass:
      accent1: '#00c6ff'
      accent2: '#0072ff'
  green:
    sass:
      accent1: '#12db5d'
      accent2: '#11998e'
  navy:
    sass:
      accent1: '#004e92'
      accent2: '#000428'
  violet:
    sass:
      accent1: '#8e2de2'
      accent2: '#4a00e0'
header:
  title: COVID 19 forecast hub
  logo_img: images/logo-covid.png
  has_nav: true
  nav_links:
    - label: Home
      url: '#'
      type: link
      has_subnav: false
    - label: About
      url: /docs/
      type: link
      has_subnav: false
    - label: Data
      url: /blog/
      type: link
      has_subnav: false
    - label: Community
      url: '/community'
      type: link
      has_subnav: false
      subnav_links:
        - label: Overview
          url: /overview/
          type: link
        - label: Showcase
          url: /showcase/
          type: link
    - label: GitHub
      url: 'https://github.com/reichlab/covid19-forecast-hub'
      type: primary
      has_subnav: false
footer:
  content: '&copy; Reichlab. All rights reserved.'
  links:
    - label: Made with Stackbit
      url: 'https://www.stackbit.com'
      type: link
      new_window: true
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      type: icon
      icon_class: fa-twitter
      new_window: true
    - label: GitHub
      url: 'https://github.com/reichlab/covid19-forecast-hub'
      type: icon
      icon_class: fa-github
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
  - deploy.sh
